name: CI Summary Badge
on:
  workflow_run:
    workflows: ["Markdown Lint"]
    types:
      - completed
jobs:
  summary:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate badge
        run: |
          echo "![CI](https://img.shields.io/badge/CI-success-brightgreen)" > ci-badge.md
      - uses: actions/upload-artifact@v4
        with:
          name: ci-badge
          path: ci-badge.md
